[package]
name = "simple_program"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
borsh = { version = "1.5.1", features = ["derive"] }
solana-contract = { path = "../" }
solana-program = "2.0.9"
